import { DataCenter } from "../types/dataCenter";

export const dataCenters: DataCenter[] = [
  // United States
  {
    name: "New York",
    country: "United States",
    region: "North America",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2", "HIPAA"],
    powerCapacity: 70,
    redundancy: "2N+2",
    networkProviders: ["Verizon", "AT&T", "Sprint"],
    load: 92,
    lat: 40.7128,
    lng: -74.006,
    totalStorage: 65000,
    usedStorage: 56000,
    specs: {
      servers: 22000,
      racks: 2000,
      coolingCapacity: 65,
      backupGenerators: 14,
    },
  },
  {
    name: "Silicon Valley",
    country: "United States",
    region: "North America",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2", "HIPAA"],
    powerCapacity: 75,
    redundancy: "2N+2",
    networkProviders: ["AT&T", "Comcast", "Level 3"],
    load: 88,
    lat: 37.3875,
    lng: -122.0575,
    totalStorage: 70000,
    usedStorage: 58000,
    specs: {
      servers: 24000,
      racks: 2200,
      coolingCapacity: 70,
      backupGenerators: 16,
    },
  },
  {
    name: "Dallas",
    country: "United States",
    region: "North America",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    powerCapacity: 65,
    redundancy: "2N+2",
    networkProviders: ["AT&T", "Verizon", "CenturyLink"],
    load: 85,
    lat: 32.7767,
    lng: -96.797,
    totalStorage: 55000,
    usedStorage: 45000,
    specs: {
      servers: 18000,
      racks: 1600,
      coolingCapacity: 60,
      backupGenerators: 12,
    },
  },

  // Europe
  {
    name: "London",
    country: "United Kingdom",
    region: "Europe",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2", "GDPR Compliant"],
    powerCapacity: 65,
    redundancy: "2N+2",
    networkProviders: ["BT", "Vodafone", "Three"],
    load: 89,
    lat: 51.5074,
    lng: -0.1278,
    totalStorage: 62000,
    usedStorage: 53000,
    specs: {
      servers: 20000,
      racks: 1800,
      coolingCapacity: 60,
      backupGenerators: 12,
    },
  },
  {
    name: "Frankfurt",
    country: "Germany",
    region: "Europe",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2", "GDPR Compliant"],
    powerCapacity: 60,
    redundancy: "2N+2",
    networkProviders: ["Deutsche Telekom", "Vodafone", "O2"],
    load: 90,
    lat: 50.1109,
    lng: 8.6821,
    totalStorage: 58000,
    usedStorage: 49000,
    specs: {
      servers: 18000,
      racks: 1600,
      coolingCapacity: 55,
      backupGenerators: 12,
    },
  },
  {
    name: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2", "GDPR Compliant"],
    powerCapacity: 55,
    redundancy: "2N+2",
    networkProviders: ["KPN", "Vodafone", "T-Mobile"],
    load: 87,
    lat: 52.3676,
    lng: 4.9041,
    totalStorage: 50000,
    usedStorage: 42000,
    specs: {
      servers: 16000,
      racks: 1400,
      coolingCapacity: 50,
      backupGenerators: 10,
    },
  },

  // Asia Pacific
  {
    name: "Tokyo",
    country: "Japan",
    region: "East Asia",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    powerCapacity: 55,
    redundancy: "2N+1",
    networkProviders: ["NTT", "KDDI", "SoftBank"],
    load: 88,
    lat: 35.6762,
    lng: 139.6503,
    totalStorage: 52000,
    usedStorage: 44000,
    specs: {
      servers: 16000,
      racks: 1400,
      coolingCapacity: 50,
      backupGenerators: 10,
    },
  },
  {
    name: "Seoul",
    country: "South Korea",
    region: "East Asia",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    powerCapacity: 50,
    redundancy: "2N+1",
    networkProviders: ["SK Telecom", "KT", "LG U+"],
    load: 86,
    lat: 37.5665,
    lng: 126.978,
    totalStorage: 48000,
    usedStorage: 40000,
    specs: {
      servers: 15000,
      racks: 1300,
      coolingCapacity: 45,
      backupGenerators: 9,
    },
  },
  {
    name: "Singapore Central",
    country: "Singapore",
    region: "Southeast Asia",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2", "SS 564"],
    powerCapacity: 60,
    redundancy: "2N+2",
    networkProviders: ["Singtel", "StarHub", "M1"],
    load: 91,
    lat: 1.3521,
    lng: 103.8198,
    totalStorage: 55000,
    usedStorage: 47000,
    specs: {
      servers: 18000,
      racks: 1500,
      coolingCapacity: 55,
      backupGenerators: 10,
    },
  },

  // South Asia
  {
    name: "Mumbai",
    country: "India",
    region: "South Asia",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    powerCapacity: 50,
    redundancy: "2N+1",
    networkProviders: ["Airtel", "Tata", "Reliance"],
    load: 78,
    lat: 19.076,
    lng: 72.8777,
    totalStorage: 50000,
    usedStorage: 39000,
    specs: {
      servers: 15000,
      racks: 1200,
      coolingCapacity: 45,
      backupGenerators: 8,
    },
  },
  {
    name: "Bangalore",
    country: "India",
    region: "South Asia",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    powerCapacity: 45,
    redundancy: "2N+1",
    networkProviders: ["Airtel", "Jio", "BSNL"],
    load: 82,
    lat: 12.9716,
    lng: 77.5946,
    totalStorage: 45000,
    usedStorage: 36000,
    specs: {
      servers: 14000,
      racks: 1100,
      coolingCapacity: 40,
      backupGenerators: 7,
    },
  },
  {
    name: "Dhaka",
    country: "Bangladesh",
    region: "South Asia",
    status: "Operational",
    tier: "Tier 3",
    certifications: ["ISO 27001", "PCI DSS"],
    powerCapacity: 40,
    redundancy: "2N",
    networkProviders: ["BTCL", "Link3", "BanglaNet"],
    load: 82,
    lat: 23.8103,
    lng: 90.4125,
    totalStorage: 38000,
    usedStorage: 31000,
    specs: {
      servers: 12000,
      racks: 1000,
      coolingCapacity: 35,
      backupGenerators: 6,
    },
  },
  {
    name: "Chittagong",
    country: "Bangladesh",
    region: "South Asia",
    status: "Operational",
    tier: "Tier 3",
    certifications: ["ISO 27001", "PCI DSS"],
    powerCapacity: 35,
    redundancy: "2N",
    networkProviders: ["BTCL", "Link3"],
    load: 79,
    lat: 22.3569,
    lng: 91.7832,
    totalStorage: 32000,
    usedStorage: 25000,
    specs: {
      servers: 10000,
      racks: 800,
      coolingCapacity: 30,
      backupGenerators: 5,
    },
  },
  {
    name: "Satkhira",
    country: "Bangladesh",
    region: "South Asia",
    status: "Operational",
    tier: "Tier 3",
    certifications: ["ISO 27001"],
    powerCapacity: 30,
    redundancy: "N+1",
    networkProviders: ["BTCL", "Link3"],
    load: 75,
    lat: 22.7185,
    lng: 89.0705,
    totalStorage: 25000,
    usedStorage: 18000,
    specs: {
      servers: 8000,
      racks: 600,
      coolingCapacity: 25,
      backupGenerators: 4,
    },
  },

  // Oceania
  {
    name: "Sydney",
    country: "Australia",
    region: "Oceania",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    powerCapacity: 45,
    redundancy: "2N+1",
    networkProviders: ["Telstra", "Optus", "TPG"],
    load: 84,
    lat: -33.8688,
    lng: 151.2093,
    totalStorage: 45000,
    usedStorage: 37000,
    specs: {
      servers: 14000,
      racks: 1200,
      coolingCapacity: 40,
      backupGenerators: 7,
    },
  },
  {
    name: "Melbourne",
    country: "Australia",
    region: "Oceania",
    status: "Operational",
    tier: "Tier 4",
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    powerCapacity: 40,
    redundancy: "2N+1",
    networkProviders: ["Telstra", "Optus", "Vodafone"],
    load: 81,
    lat: -37.8136,
    lng: 144.9631,
    totalStorage: 40000,
    usedStorage: 32000,
    specs: {
      servers: 12000,
      racks: 1000,
      coolingCapacity: 35,
      backupGenerators: 6,
    },
  },
];
